In [1]:
import pandas as pd 
import numpy as np 
from scipy.stats import skew

In [3]:
df1 = pd.read_csv('data1.csv')
df1

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [4]:
df2 = pd.read_csv('data2.csv')
df2

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

# Merge datasets

In [65]:
merged_data = pd.merge(df1, df2, on='instant' , how = 'inner')
merged_data

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  Unnamed: 0   atemp   hum  windspeed  casual  registered  cnt  
0    0.24           0  0.2879  0.81     0.0000       3          13   16  
1    0.22           1  0.2727  0.80     0.0000       8          32   40  
2    0.22           2  0.2727  0.80     0.0000       5          27   32  
3    0.24           3  0.2879  0.75     0.0000       3          10   13  
4    0.24           4  0.2879  0.75     0.0000       0           1    1  
..    ...         ...     ...   ...        ...     ...         ...  ...  
605  0.18         605  0.2121  0.93     0.1045       0          30   30  
606  0.18         606  0.2121  0.93     0.1045       1          28   29  
607  0.18         607  0.2121  0.93     0.1045       0          31   31  
608  0.22         608  0.2727  0.80     0.0000       2          36   38  
609  0.20         609  0.2576  0.86     0.0000       1          40   41  

[610 rows x 17 columns]

# Concatenated data

In [66]:
concatenated_data = pd.concat([df1, df2], axis=1)
concatenated_data

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  01-01-2011       1   0     1   0    False        6           1   
1          2  01-01-2011       1   0     1   1    False        6           1   
2          3  01-01-2011       1   0     1   2    False        6           1   
3          4  01-01-2011       1   0     1   3    False        6           1   
4          5  01-01-2011       1   0     1   4    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
605      606  28-01-2011       1   0     1  11    False        5           3   
606      607  28-01-2011       1   0     1  12    False        5           3   
607      608  28-01-2011       1   0     1  13    False        5           3   
608      609  28-01-2011       1   0     1  14    False        5           3   
609      610  28-01-2011       1   0     1  15    False        5           2   

     temp  Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  \
0    0.24           0        1  0.2879  0.81     0.0000       3          13   
1    0.22           1        2  0.2727  0.80     0.0000       8          32   
2    0.22           2        3  0.2727  0.80     0.0000       5          27   
3    0.24           3        4  0.2879  0.75     0.0000       3          10   
4    0.24           4        5  0.2879  0.75     0.0000       0           1   
..    ...         ...      ...     ...   ...        ...     ...         ...   
605  0.18         605      606  0.2121  0.93     0.1045       0          30   
606  0.18         606      607  0.2121  0.93     0.1045       1          28   
607  0.18         607      608  0.2121  0.93     0.1045       0          31   
608  0.22         608      609  0.2727  0.80     0.0000       2          36   
609  0.20         609      610  0.2576  0.86     0.0000       1          40   

     cnt  
0     16  
1     40  
2     32  
3     13  
4      1  
..   ...  
605   30  
606   29  
607   31  
608   38  
609   41  

[610 rows x 18 columns]

# Identify unique values


In [57]:
unique_values = df['instant'].unique() #Finding Unique Values In Instant colm
unique_values

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [59]:
unique_values = df['atemp'].unique()   #Finding Unique Values In temprature colum
unique_values

array([0.2879, 0.2727, 0.2576,    nan, 0.3485, 0.3939, 0.3333, 0.4242,
       0.4545, 0.4394, 0.4091, 0.2273, 0.2121, 0.197 , 0.1364, 0.1061,
       0.1212, 0.1667, 0.1818, 0.2424, 0.1515, 0.3182, 0.0606, 0.0758,
       0.0909, 0.303 , 0.0303, 0.0455, 0.    , 0.0152])

In [60]:
unique_values = df['windspeed'].unique()    #Finding Unique Values In windspeed colum
unique_values

array([0.    , 0.0896, 0.2537, 0.2836, 0.2985, 0.194 , 0.2239, 0.1343,
       0.1642, 0.3284, 0.4478, 0.3582, 0.4179, 0.3881, 0.1045, 0.4925,
       0.5522, 0.4627, 0.5224, 0.5821])

In [61]:
unique_values = df['hum'].unique()    #Finding Unique Values In humidity colum
unique_values

array([0.81, 0.8 , 0.75, 0.86, 0.76, 0.77, 0.72, 0.82, 0.88, 0.87, 0.94,
       1.  , 0.71, 0.66, 0.57, 0.46, 0.42, 0.39, 0.44, 0.47, 0.5 , 0.43,
       0.4 , 0.35, 0.3 , 0.32, 0.64, 0.69, 0.55, 0.59, 0.63, 0.68, 0.74,
       0.51, 0.56, 0.52, 0.49, 0.48, 0.37, 0.33, 0.28, 0.38, 0.36, 0.93,
       0.29, 0.53, 0.34, 0.54, 0.41, 0.45, 0.92, 0.62, 0.58, 0.61, 0.6 ,
       0.65, 0.7 , 0.27, 0.21, 0.25, 0.26])

# Drop unnecessary columns

In [67]:
cleaned_data = df1.drop(['yr', 'weathersit'], axis=1)  #From data1 removed year and weathersit colum
cleaned_data

instant      dteday  season  mnth  hr  holiday  weekday  temp
0          1  01-01-2011       1     1   0    False        6  0.24
1          2  01-01-2011       1     1   1    False        6  0.22
2          3  01-01-2011       1     1   2    False        6  0.22
3          4  01-01-2011       1     1   3    False        6  0.24
4          5  01-01-2011       1     1   4    False        6  0.24
..       ...         ...     ...   ...  ..      ...      ...   ...
605      606  28-01-2011       1     1  11    False        5  0.18
606      607  28-01-2011       1     1  12    False        5  0.18
607      608  28-01-2011       1     1  13    False        5  0.18
608      609  28-01-2011       1     1  14    False        5  0.22
609      610  28-01-2011       1     1  15    False        5  0.20

[610 rows x 8 columns]

In [73]:
cleaned_data = df2.drop(['instant','casual'], axis=1)  #From data2 removed instant and casual colum 
cleaned_data

Unnamed: 0   atemp   hum  windspeed  registered  cnt
0             0  0.2879  0.81     0.0000          13   16
1             1  0.2727  0.80     0.0000          32   40
2             2  0.2727  0.80     0.0000          27   32
3             3  0.2879  0.75     0.0000          10   13
4             4  0.2879  0.75     0.0000           1    1
..          ...     ...   ...        ...         ...  ...
605         605  0.2121  0.93     0.1045          30   30
606         606  0.2121  0.93     0.1045          28   29
607         607  0.2121  0.93     0.1045          31   31
608         608  0.2727  0.80     0.0000          36   38
609         609  0.2576  0.86     0.0000          40   41

[610 rows x 6 columns]

# Check the dimension of the dataset


In [75]:
data1 = df1.shape
data1

(610, 10)

In [79]:
data2 = df2.shape
data2

(610, 8)

# Check the datatype of the dataset


In [86]:
data1 = df1.dtypes    #Checking the data type of dataset1
data1

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday          bool
weekday         int64
weathersit      int64
temp          float64
dtype: object

In [87]:
data2 = df2.dtypes    #Checking the data type of dataset2
data2

Unnamed: 0      int64
instant         int64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

# Check datatype summary


In [89]:
data1 = df1.info()  #Finding data1 information 
data1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     610 non-null    int64  
 1   dteday      610 non-null    object 
 2   season      610 non-null    int64  
 3   yr          610 non-null    int64  
 4   mnth        610 non-null    int64  
 5   hr          610 non-null    int64  
 6   holiday     610 non-null    bool   
 7   weekday     610 non-null    int64  
 8   weathersit  610 non-null    int64  
 9   temp        610 non-null    float64
dtypes: bool(1), float64(1), int64(7), object(1)
memory usage: 43.6+ KB


In [90]:
data2 = df2.info()  #Finding data2 information
data2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  610 non-null    int64  
 1   instant     610 non-null    int64  
 2   atemp       599 non-null    float64
 3   hum         610 non-null    float64
 4   windspeed   610 non-null    float64
 5   casual      610 non-null    int64  
 6   registered  610 non-null    int64  
 7   cnt         610 non-null    int64  
dtypes: float64(3), int64(5)
memory usage: 38.2 KB


# work on central Tendency

***Finding central tendency of dataset 1***

***MEAN***

In [95]:
data1 = df1['temp'].mean()
data1

0.19688524590163933

In [97]:
data1 = df1['instant'].mean()
data1

305.5

***MEDIAN***

In [98]:
data1 = df1['temp'].median()
data1

0.2

In [99]:
data1 = df1['instant'].median()
data1

305.5

***MODE***

In [100]:
data1 = df1['temp'].mode()
data1

0    0.2
Name: temp, dtype: float64

In [102]:
data1 = df1['instant'].mode()
data1

0        1
1        2
2        3
3        4
4        5
      ... 
605    606
606    607
607    608
608    609
609    610
Name: instant, Length: 610, dtype: int64

***QUARTILES***

In [35]:
q1 =df1['temp'].quantile(.25)
q1

0.16

In [36]:
q2 =df1['instant'].quantile(.75)
q2

457.75

In [38]:
q3 =df1['temp'].quantile(.125)
q3

0.12

***SKEWNESS***


In [17]:
skewness_df1 = df1.skew()
print("Skewness for the entire DataFrame:")
print(skewness_df1)

Skewness for the entire DataFrame:
instant       0.000000
dteday             NaN
season        0.000000
yr            0.000000
mnth          0.000000
hr           -0.072059
holiday       4.750637
weekday       0.026403
weathersit    1.050244
temp          0.665087
dtype: float64


***CORRELATION***

In [18]:
correlation_matrix = df1.corr()
print("Correlation matrix for the entire DataFrame:")
print(correlation_matrix)

Correlation matrix for the entire DataFrame:
             instant  dteday  season  yr  mnth        hr   holiday   weekday  \
instant     1.000000     NaN     NaN NaN   NaN  0.025355  0.090792  0.015448   
dteday           NaN     NaN     NaN NaN   NaN       NaN       NaN       NaN   
season           NaN     NaN     NaN NaN   NaN       NaN       NaN       NaN   
yr               NaN     NaN     NaN NaN   NaN       NaN       NaN       NaN   
mnth             NaN     NaN     NaN NaN   NaN       NaN       NaN       NaN   
hr          0.025355     NaN     NaN NaN   NaN  1.000000 -0.008722 -0.021792   
holiday     0.090792     NaN     NaN NaN   NaN -0.008722  1.000000 -0.194864   
weekday     0.015448     NaN     NaN NaN   NaN -0.021792 -0.194864  1.000000   
weathersit  0.162506     NaN     NaN NaN   NaN -0.056370  0.217058  0.065414   
temp       -0.314224     NaN     NaN NaN   NaN  0.165148 -0.052444  0.040457   

            weathersit      temp  
instant       0.162506 -0.314224  
dted

***Finding central tendency of dataset 2***

***MEAN***

In [103]:
data2 = df2['atemp'].mean()
data2

0.19993489148580967

In [104]:
data2 = df2['hum'].mean()
data2

0.5624754098360656

In [105]:
data2 = df2['windspeed'].mean()
data2

0.20485098360655737

In [106]:
data2 = df2['registered'].mean()
data2

51.06885245901639

***MEDIAN***

In [107]:
data2 = df2['atemp'].median()
data2

0.197

In [109]:
data2 = df2['hum'].median()
data2

0.52

In [110]:
data2 = df2['windspeed'].median()
data2

0.194

In [112]:
data2 = df2['registered'].median()
data2

43.0

***MODE***

In [113]:
data2 = df2['atemp'].mode()
data2

0    0.197
Name: atemp, dtype: float64

In [114]:
data2 = df2['hum'].mode()
data2

0    0.47
Name: hum, dtype: float64

In [115]:
data2 = df2['windspeed'].mode()
data2

0    0.1642
Name: windspeed, dtype: float64

In [116]:
data2 = df2['registered'].mode()
data2

0    1
Name: registered, dtype: int64

***QAURTILE***

In [42]:
q1 =df2['registered'].quantile(.25)
q1

14.0

In [43]:
q2 =df2['atemp'].quantile(.75)
q2

0.2424

In [44]:
q3 =df2['cnt'].quantile(.125)
q3

4.0

***SKEWNESS***

In [19]:
skewness_df2 = df2.skew()
print("Skewness for the entire DataFrame:")
print(skewness_df2)

Skewness for the entire DataFrame:
Unnamed: 0    0.000000
instant       0.000000
atemp         0.555599
hum           0.609553
windspeed     0.339029
casual        2.712869
registered    1.428875
cnt           1.243563
dtype: float64


***CORRELATION***

In [20]:
correlation_matrix = df2.corr()
print("Correlation matrix for the entire DataFrame:")
print(correlation_matrix)

Correlation matrix for the entire DataFrame:
            Unnamed: 0   instant     atemp       hum  windspeed    casual  \
Unnamed: 0    1.000000  1.000000 -0.277607  0.045119  -0.029262 -0.088926   
instant       1.000000  1.000000 -0.277607  0.045119  -0.029262 -0.088926   
atemp        -0.277607 -0.277607  1.000000  0.302530  -0.246309  0.391066   
hum           0.045119  0.045119  0.302530  1.000000  -0.307205 -0.204634   
windspeed    -0.029262 -0.029262 -0.246309 -0.307205   1.000000  0.120109   
casual       -0.088926 -0.088926  0.391066 -0.204634   0.120109  1.000000   
registered    0.047670  0.047670  0.145876 -0.228278   0.038115  0.304894   
cnt           0.034055  0.034055  0.189119 -0.243876   0.051733  0.418852   

            registered       cnt  
Unnamed: 0    0.047670  0.034055  
instant       0.047670  0.034055  
atemp         0.145876  0.189119  
hum          -0.228278 -0.243876  
windspeed     0.038115  0.051733  
casual        0.304894  0.418852  
registered    1.

# Working on Data 3

In [23]:
df3 = pd.read_csv('data3.csv')
df3

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0        620  29-01-2011       1   0     1   1    False        6           1   
1        621  29-01-2011       1   0     1   2    False        6           1   
2        622  29-01-2011       1   0     1   3    False        6           1   
3        623  29-01-2011       1   0     1   4    False        6           1   
4        624  29-01-2011       1   0     1   6    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
385      615  28-01-2011       1   0     1  20    False        5           2   
386      616  28-01-2011       1   0     1  21    False        5           2   
387      617  28-01-2011       1   0     1  22    False        5           1   
388      618  28-01-2011       1   0     1  23    False        5           1   
389      619  29-01-2011       1   0     1   0    False        6           1   

     temp   atemp   hum  windspeed  casual  registered  cnt  
0    0.22  0.2273  0.64     0.1940       0          20   20  
1    0.22  0.2273  0.64     0.1642       0          15   15  
2    0.20  0.2121  0.64     0.1343       3           5    8  
3    0.16  0.1818  0.69     0.1045       1           2    3  
4    0.16  0.1818  0.64     0.1343       0           2    2  
..    ...     ...   ...        ...     ...         ...  ...  
385  0.24  0.2273  0.70     0.1940       1          61   62  
386  0.22  0.2273  0.75     0.1343       1          57   58  
387  0.24  0.2121  0.65     0.3582       0          26   26  
388  0.24  0.2273  0.60     0.2239       1          22   23  
389  0.22  0.1970  0.64     0.3582       2          26   28  

[390 rows x 16 columns]

# merge datasets 

In [10]:
merged_data = pd.merge(df2,df3 , on='hum' , how = 'inner') # Mergeing hum(humidity) from dataset 2 into dataset 3 
merged_data

Unnamed: 0  instant_x  atemp_x   hum  windspeed_x  casual_x  \
0              0          1   0.2879  0.81       0.0000         3   
1              0          1   0.2879  0.81       0.0000         3   
2              0          1   0.2879  0.81       0.0000         3   
3              0          1   0.2879  0.81       0.0000         3   
4              0          1   0.2879  0.81       0.0000         3   
...          ...        ...      ...   ...          ...       ...   
5619         471        472   0.1364  0.26       0.3582         0   
5620         517        518   0.1364  0.26       0.3284         9   
5621         517        518   0.1364  0.26       0.3284         9   
5622         518        519   0.1061  0.26       0.3881         5   
5623         518        519   0.1061  0.26       0.3881         5   

      registered_x  cnt_x  instant_y      dteday  ...  hr  holiday  weekday  \
0               13     16        706  01-02-2011  ...  18    False        2   
1               13     16        707  01-02-2011  ...  19    False        2   
2               13     16        852  07-02-2011  ...  22    False        1   
3               13     16        853  07-02-2011  ...  23    False        1   
4               13     16        859  08-02-2011  ...   5    False        2   
...            ...    ...        ...         ...  ...  ..      ...      ...   
5619            97     97        936  11-02-2011  ...  14    False        5   
5620            56     65        917  10-02-2011  ...  17    False        4   
5621            56     65        936  11-02-2011  ...  14    False        5   
5622            50     55        917  10-02-2011  ...  17    False        4   
5623            50     55        936  11-02-2011  ...  14    False        5   

      weathersit  temp  atemp_y  windspeed_y  casual_y  registered_y  cnt_y  
0              2  0.24   0.2576       0.1045         3           165    168  
1              2  0.24   0.2424       0.1343         3           105    108  
2              1  0.28   0.3030       0.0896         3            34     37  
3              2  0.30   0.3333       0.0000         6            19     25  
4              1  0.26   0.2273       0.3284         0             2      2  
...          ...   ...      ...          ...       ...           ...    ...  
5619           1  0.30   0.2879       0.2537        17            67     84  
5620           1  0.18   0.1818       0.1940         6           159    165  
5621           1  0.30   0.2879       0.2537        17            67     84  
5622           1  0.18   0.1818       0.1940         6           159    165  
5623           1  0.30   0.2879       0.2537        17            67     84  

[5624 rows x 23 columns]

# Concatenated data

In [11]:
concatenated_data = pd.concat([df2, df3], axis=1)
concatenated_data

C:\Users\HP\anaconda3\lib\site-packages\IPython\lib\pretty.py:778: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  output = repr(obj)
C:\Users\HP\anaconda3\lib\site-packages\IPython\core\formatters.py:342: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  return method()


Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt  \
0             0        1  0.2879  0.81     0.0000       3          13   16   
1             1        2  0.2727  0.80     0.0000       8          32   40   
2             2        3  0.2727  0.80     0.0000       5          27   32   
3             3        4  0.2879  0.75     0.0000       3          10   13   
4             4        5  0.2879  0.75     0.0000       0           1    1   
..          ...      ...     ...   ...        ...     ...         ...  ...   
605         605      606  0.2121  0.93     0.1045       0          30   30   
606         606      607  0.2121  0.93     0.1045       1          28   29   
607         607      608  0.2121  0.93     0.1045       0          31   31   
608         608      609  0.2727  0.80     0.0000       2          36   38   
609         609      610  0.2576  0.86     0.0000       1          40   41   

     instant      dteday  ...  holiday  weekday  weathersit  temp   atemp  \
0      620.0  29-01-2011  ...    False      6.0         1.0  0.22  0.2273   
1      621.0  29-01-2011  ...    False      6.0         1.0  0.22  0.2273   
2      622.0  29-01-2011  ...    False      6.0         1.0  0.20  0.2121   
3      623.0  29-01-2011  ...    False      6.0         1.0  0.16  0.1818   
4      624.0  29-01-2011  ...    False      6.0         1.0  0.16  0.1818   
..       ...         ...  ...      ...      ...         ...   ...     ...   
605      NaN         NaN  ...      NaN      NaN         NaN   NaN     NaN   
606      NaN         NaN  ...      NaN      NaN         NaN   NaN     NaN   
607      NaN         NaN  ...      NaN      NaN         NaN   NaN     NaN   
608      NaN         NaN  ...      NaN      NaN         NaN   NaN     NaN   
609      NaN         NaN  ...      NaN      NaN         NaN   NaN     NaN   

      hum  windspeed  casual  registered   cnt  
0    0.64     0.1940     0.0        20.0  20.0  
1    0.64     0.1642     0.0        15.0  15.0  
2    0.64     0.1343     3.0         5.0   8.0  
3    0.69     0.1045     1.0         2.0   3.0  
4    0.64     0.1343     0.0         2.0   2.0  
..    ...        ...     ...         ...   ...  
605   NaN        NaN     NaN         NaN   NaN  
606   NaN        NaN     NaN         NaN   NaN  
607   NaN        NaN     NaN         NaN   NaN  
608   NaN        NaN     NaN         NaN   NaN  
609   NaN        NaN     NaN         NaN   NaN  

[610 rows x 24 columns]

***concatenated 2 colum froms dataset2 and dataset3***

In [13]:
concatenated_df = pd.concat([df2['instant'], df3['temp']], axis=0)
concatenated_df

0      1.00
1      2.00
2      3.00
3      4.00
4      5.00
       ... 
385    0.24
386    0.22
387    0.24
388    0.24
389    0.22
Length: 1000, dtype: float64

# Identify unique values

In [14]:
unique_values = df3['temp'].unique() #Finding Unique Values In temp from dataset3 colum
unique_values

array([0.22, 0.2 , 0.16, 0.18, 0.24, 0.14, 0.3 , 0.28, 0.26, 0.34, 0.38,
       0.36, 0.32, 0.12, 0.1 , 0.08, 0.06, 0.4 , 0.42])

In [15]:
unique_values = df3['atemp'].unique() #Finding Unique Values In temp from dataset3 colum
unique_values

array([0.2273, 0.2121, 0.1818, 0.197 , 0.2424, 0.2879, 0.2727, 0.3182,
       0.303 , 0.3333, 0.2576, 0.1667, 0.1364, 0.1515, 0.3939, 0.1212,
       0.3636, 0.3485, 0.1061, 0.0758, 0.4091, 0.4242])

In [17]:
unique_values = df3['hum'].unique() #Finding Unique Values In humidity from dataset3 colum
unique_values

array([0.64, 0.69, 0.59, 0.55, 0.6 , 0.74, 0.8 , 0.93, 0.86, 0.75, 0.52,
       0.61, 0.56, 0.65, 0.7 , 0.81, 0.87, 1.  , 0.82, 0.76, 0.71, 0.53,
       0.42, 0.45, 0.48, 0.47, 0.44, 0.4 , 0.43, 0.5 , 0.37, 0.51, 0.63,
       0.49, 0.46, 0.62, 0.57, 0.54, 0.66, 0.38, 0.32, 0.35, 0.33, 0.36,
       0.39, 0.34, 0.29, 0.27, 0.25, 0.26, 0.28, 0.31, 0.68, 0.73, 0.21,
       0.24, 0.41, 0.3 ])

In [18]:
unique_values = df3['windspeed'].unique() #Finding Unique Values In windspeed from dataset3 colum
unique_values

array([0.194 , 0.1642, 0.1343, 0.1045, 0.0896, 0.2537, 0.    , 0.2836,
       0.2239, 0.3284, 0.2985, 0.3881, 0.5224, 0.5522, 0.4925, 0.4478,
       0.3582, 0.4179, 0.4627, 0.5821])

# Drop unnecessary columns

In [19]:
cleaned_data = df3.drop(['atemp', 'casual'], axis=1)  #From data3 removed atemp and casual colum
cleaned_data

instant      dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0        620  29-01-2011       1   0     1   1    False        6           1   
1        621  29-01-2011       1   0     1   2    False        6           1   
2        622  29-01-2011       1   0     1   3    False        6           1   
3        623  29-01-2011       1   0     1   4    False        6           1   
4        624  29-01-2011       1   0     1   6    False        6           1   
..       ...         ...     ...  ..   ...  ..      ...      ...         ...   
385      615  28-01-2011       1   0     1  20    False        5           2   
386      616  28-01-2011       1   0     1  21    False        5           2   
387      617  28-01-2011       1   0     1  22    False        5           1   
388      618  28-01-2011       1   0     1  23    False        5           1   
389      619  29-01-2011       1   0     1   0    False        6           1   

     temp   hum  windspeed  registered  cnt  
0    0.22  0.64     0.1940          20   20  
1    0.22  0.64     0.1642          15   15  
2    0.20  0.64     0.1343           5    8  
3    0.16  0.69     0.1045           2    3  
4    0.16  0.64     0.1343           2    2  
..    ...   ...        ...         ...  ...  
385  0.24  0.70     0.1940          61   62  
386  0.22  0.75     0.1343          57   58  
387  0.24  0.65     0.3582          26   26  
388  0.24  0.60     0.2239          22   23  
389  0.22  0.64     0.3582          26   28  

[390 rows x 14 columns]

# Check the dimension of the datase

In [21]:
data_dimension = df3.shape
data_dimension

(390, 16)

# Check the datatype of the dataset

In [22]:
database_type = df3.dtypes
database_type

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday          bool
weekday         int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

# Check datatype summary

In [23]:
data_summary = df3.info()
data_summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     390 non-null    int64  
 1   dteday      390 non-null    object 
 2   season      390 non-null    int64  
 3   yr          390 non-null    int64  
 4   mnth        390 non-null    int64  
 5   hr          390 non-null    int64  
 6   holiday     390 non-null    bool   
 7   weekday     390 non-null    int64  
 8   weathersit  390 non-null    int64  
 9   temp        390 non-null    float64
 10  atemp       390 non-null    float64
 11  hum         390 non-null    float64
 12  windspeed   390 non-null    float64
 13  casual      390 non-null    int64  
 14  registered  390 non-null    int64  
 15  cnt         390 non-null    int64  
dtypes: bool(1), float64(4), int64(10), object(1)
memory usage: 46.2+ KB


# Missing values on database 3 

In [26]:
missing_values = df3.isnull()   # Returns a DataFrame of True/False values
missing_values 

instant  dteday  season     yr   mnth     hr  holiday  weekday  \
0      False   False   False  False  False  False    False    False   
1      False   False   False  False  False  False    False    False   
2      False   False   False  False  False  False    False    False   
3      False   False   False  False  False  False    False    False   
4      False   False   False  False  False  False    False    False   
..       ...     ...     ...    ...    ...    ...      ...      ...   
385    False   False   False  False  False  False    False    False   
386    False   False   False  False  False  False    False    False   
387    False   False   False  False  False  False    False    False   
388    False   False   False  False  False  False    False    False   
389    False   False   False  False  False  False    False    False   

     weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0         False  False  False  False      False   False       False  False  
1         False  False  False  False      False   False       False  False  
2         False  False  False  False      False   False       False  False  
3         False  False  False  False      False   False       False  False  
4         False  False  False  False      False   False       False  False  
..          ...    ...    ...    ...        ...     ...         ...    ...  
385       False  False  False  False      False   False       False  False  
386       False  False  False  False      False   False       False  False  
387       False  False  False  False      False   False       False  False  
388       False  False  False  False      False   False       False  False  
389       False  False  False  False      False   False       False  False  

[390 rows x 16 columns]

In [27]:
missing_counts = df3.isnull().sum()    # Count missing values in each column
missing_counts

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

# work on central Tendency

***MEAN***

In [24]:
MEAN =df3['registered'].mean()
MEAN

57.0025641025641

In [25]:
MEAN =df3['cnt'].mean()
MEAN

62.57948717948718

In [26]:
MEAN =df3['windspeed'].mean()
MEAN

0.17941589743589745

***MEDIAN***

In [27]:
median = df3['registered'].median()
median

48.0

In [28]:
median = df3['cnt'].median()
median

52.0

In [29]:
median = df3['windspeed'].median()
median

0.1642

***MODE***

In [30]:
mode = df3['registered'].mode()
mode

0    1
Name: registered, dtype: int64

In [31]:
mode = df3['cnt'].mode()
mode

0    2
Name: cnt, dtype: int64

In [32]:
mode = df3['windspeed'].mode()
mode

0    0.0
Name: windspeed, dtype: float64

***QAURTILE***

In [33]:
q1 =df3['registered'].quantile(.25)
q1

17.0

In [35]:
q2 =df3['cnt'].quantile(.75)
q2

88.75

In [36]:
q3 =df3['windspeed'].quantile(.125)
q3

0.0

***SKEWNESS***

In [37]:
skewness_df3 = df3.skew()
print("Skewness for the entire DataFrame:")
print(skewness_df3)

Skewness for the entire DataFrame:
instant       0.000000
season        0.000000
yr            0.000000
mnth         -1.505798
hr           -0.050086
holiday       0.000000
weekday       0.014906
weathersit    1.037234
temp          0.479548
atemp         0.440540
hum           0.161484
windspeed     0.620359
casual        3.413724
registered    1.115912
cnt           0.987140
dtype: float64


C:\Users\HP\AppData\Local\Temp\ipykernel_25372\3115036028.py:1: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  skewness_df3 = df3.skew()


***CORRELATION***

In [38]:
correlation_matrix = df3.corr()
print("Correlation matrix for the entire DataFrame:")
print(correlation_matrix)

Correlation matrix for the entire DataFrame:
             instant  season  yr      mnth        hr  holiday   weekday  \
instant     1.000000     NaN NaN  0.692823 -0.018596      NaN  0.000053   
season           NaN     NaN NaN       NaN       NaN      NaN       NaN   
yr               NaN     NaN NaN       NaN       NaN      NaN       NaN   
mnth        0.692823     NaN NaN  1.000000 -0.056458      NaN  0.093148   
hr         -0.018596     NaN NaN -0.056458  1.000000      NaN  0.050662   
holiday          NaN     NaN NaN       NaN       NaN      NaN       NaN   
weekday     0.000053     NaN NaN  0.093148  0.050662      NaN  1.000000   
weathersit -0.220022     NaN NaN  0.027074 -0.054857      NaN  0.052128   
temp        0.164053     NaN NaN  0.126446  0.278821      NaN -0.289220   
atemp       0.117704     NaN NaN  0.091299  0.225257      NaN -0.319828   
hum        -0.403658     NaN NaN -0.125794 -0.211255      NaN  0.049960   
windspeed   0.206271     NaN NaN  0.142861  0.097096   

C:\Users\HP\AppData\Local\Temp\ipykernel_25372\1763672021.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = df3.corr()
